(() => {
  const KEY = 'threadsOpsMvpV1';
  const today = new Date();
  const iso = d => new Date(d).toISOString();
  const daysAgo = n => iso(Date.now() - n * 86400000);
  const defaultData = {
    version: 1,
    clients: [{
      id:'client-naturetea', company:'자연애한차', industry:'전통차·건강음료', target:'건강한 일상을 원하는 30~50대 직장인과 부모님 선물 고객', purpose:'전통차를 어렵지 않게 소개하고 자사몰 구매와 선물 상담으로 연결', tone:'따뜻하고 담백한 존댓말. 짧은 문장과 생활 속 장면을 활용', banned:'질병 치료, 완치, 의학적 효능을 단정하는 표현', services:'국산 원료 수제 한방차, 선물세트, 계절 블렌딩 티', references:'아침 루틴, 부모님 선물, 원료 산지 이야기', manager:'김다온 (데모)', contact:'010-0000-0000', contractStart:'2026-09-01', contractEnd:'2026-12-31', monthlyGoal:16, requests:'과장된 건강 효능 표현 금지. 제품보다 마시는 순간을 먼저 보여주세요.', threads:'https://www.threads.net/@nature_aetea', username:'nature_aetea', profileName:'자연애한차 | 매일 한 잔의 쉼', bio:'국산 원료로 천천히 우려낸 전통차. 바쁜 하루에 따뜻한 한 잔을 건네요.', lastSync:daysAgo(0), confirmed:true,
      analysis:{industry:'전통차·건강음료',target:'건강 루틴과 선물 아이디어를 찾는 30~50대',purpose:'브랜드 신뢰 형성과 선물세트 구매 전환',themes:'아침 루틴, 원료 이야기, 계절 건강 습관, 선물 상황',tone:'부드러운 존댓말, 감각적인 첫 문장, 3~5문장',hooks:'질문형, 계절 상황 제시, 의외의 생활 팁',services:'국산 원료 수제차와 명절·감사 선물세트',best:'생활 장면이 선명한 공감형 정보 콘텐츠',missing:'고객 후기, 제품 선택 가이드, 만드는 사람의 이야기',direction:'정보형과 브랜드 이야기 비중을 높이고 자연스러운 상담 유도',caution:'몸이 가벼워진다, 감기에 좋다 — 효능 단정 여부 확인 필요'}
    }],
    posts:[
      {id:'th-101',clientId:'client-naturetea',date:daysAgo(3),kind:'일반',format:'텍스트',category:'공감',text:'아침에 물 대신 따뜻한 차를 찾게 되는 날이 있어요. 거창한 루틴보다, 잔을 데우는 3분이 하루의 속도를 조금 늦춰줍니다.',url:'https://threads.net/@nature_aetea/post/101',likes:84,comments:13,reposts:9,views:1850,analyzed:true,featured:true},
      {id:'th-102',clientId:'client-naturetea',date:daysAgo(8),kind:'일반',format:'이미지',category:'정보',text:'부모님 차 선물, 향이 강한 것보다 매일 손이 가는 맛을 골라보세요. 구수한 작두콩과 은은한 대추 블렌딩은 식후에도 부담이 적어요.',url:'https://threads.net/@nature_aetea/post/102',likes:126,comments:21,reposts:18,views:2640,analyzed:true,featured:true},
      {id:'th-103',clientId:'client-naturetea',date:daysAgo(14),kind:'일반',format:'영상',category:'브랜드',text:'좋은 차는 원료 이름보다 볶는 시간을 먼저 봅니다. 오늘도 작은 불 앞에서 향이 가장 편안해지는 순간을 기다렸어요.',url:'https://threads.net/@nature_aetea/post/103',likes:97,comments:16,reposts:12,views:2190,analyzed:true,featured:false},
      {id:'th-104',clientId:'client-naturetea',date:daysAgo(20),kind:'답글',format:'텍스트',category:'정보',text:'찬물에도 우릴 수 있지만 첫 잔은 미지근한 물에 5분 정도 추천드려요.',url:'https://threads.net/@nature_aetea/post/104',likes:22,comments:4,reposts:1,views:510,analyzed:false,excluded:true},
      {id:'th-105',clientId:'client-naturetea',date:daysAgo(26),kind:'일반',format:'이미지',category:'홍보',text:'선물은 크기보다 건네는 이유가 오래 남더라고요. 감사한 분께 따뜻한 한 잔을 보낼 수 있도록 포장했습니다.',url:'https://threads.net/@nature_aetea/post/105',likes:71,comments:8,reposts:7,views:1430,analyzed:true}
    ],
    contents:[
      {id:'ct-1',clientId:'client-naturetea',title:'오후 3시, 커피 대신 따뜻한 차',hook:'오후 3시만 되면 두 번째 커피를 찾나요?',body:'오후 3시만 되면 두 번째 커피를 찾나요?\n\n오늘은 잔부터 따뜻하게 데워보세요. 구수한 차 한 잔과 5분의 여유면, 일을 멈추지 않고도 호흡을 고를 수 있어요.\n\n지금 필요한 건 더 빠른 속도가 아니라 잠깐의 온기일지도 몰라요.',type:'공감·질문형',purpose:'공감',media:'따뜻한 찻잔 사진',writeDate:'2026-09-15',deliveryDate:'2026-09-15',schedule:'2026-09-16T15:00',published:'',status:'고객 확인 중',feedback:'마지막 문장을 조금 더 담백하게 요청',before:'지금 필요한 건 카페인이 아니라 차 한 잔일지도 몰라요.',final:'지금 필요한 건 더 빠른 속도가 아니라 잠깐의 온기일지도 몰라요.',link:'',history:[{date:'2026-09-15',note:'고객 요청 반영: 카페인 직접 비교 표현 완화'}]},
      {id:'ct-2',clientId:'client-naturetea',title:'부모님 차 선물 고르는 기준 3가지',hook:'부모님 차 선물, 비싼 것보다 먼저 볼 게 있어요.',body:'부모님 차 선물, 비싼 것보다 먼저 볼 게 있어요.\n\n① 매일 마시기 편한 맛인지\n② 원료와 제조일을 확인할 수 있는지\n③ 보관이 간편한지\n\n선물은 받는 날보다 꺼내 마시는 날이 더 많으니까요.',type:'정보형',purpose:'정보',media:'선물세트 구성 사진',writeDate:'2026-09-13',deliveryDate:'2026-09-14',schedule:'2026-09-10T11:00',published:daysAgo(5),status:'발행 완료',feedback:'좋습니다. 선물 포장 사진 사용',before:'부모님 선물은 가격보다 실용성이 중요합니다.',final:'부모님 차 선물, 비싼 것보다 먼저 볼 게 있어요.',link:'https://threads.net/@nature_aetea/post/106',history:[{date:'2026-09-14',note:'승인 완료'},{date:'2026-09-10',note:'발행 완료'}]}
    ],
    performance:[{id:'pf-1',contentId:'ct-2',window:'24h',views:3280,likes:154,comments:27,follows:19,reposts:24,shares:18,profileVisits:86,clicks:31,inquiries:5,purchases:2,commentsText:'선물용으로 맛 추천 요청, 무카페인 여부 질문',reaction:'구성 기준이 명확해 저장·공유 반응이 높았음',conversion:'가격과 배송일 문의 5건',reasonHigh:'선물 선택의 어려움을 3가지 기준으로 단순화',reasonLow:'',next:'체크리스트형 후킹과 구체적인 사용 상황 재활용'}],
    requests:[{id:'rq-1',clientId:'client-naturetea',item:'추석 선물세트 세로 사진 3장',purpose:'선물 콘텐츠 이미지',contentId:'ct-2',requested:'2026-09-12',due:'2026-09-16',priority:'최우선',status:'요청 완료',reply:'포장 완료 후 전달 예정',asset:'',caution:'포장 리본 색상은 실제 제품과 동일해야 함'}],
    reports:[], settings:{apiConnected:false, includeReplies:false, includeReposts:false}
  };

  let data = load();
  let route = 'dashboard', selectedClient = data.clients[0]?.id, postView = 'card';
  const navItems = [
    ['dashboard','⌂','대시보드'],['clients','♙','고객 관리'],['analysis','◎','계정 분석'],['compose','✎','콘텐츠 작성'],['board','▦','콘텐츠 보드'],['performance','↗','성과 기록'],['reports','▤','보고서'],['requests','▧','자료 요청'],['backup','⇄','데이터 백업'],['integration','⚙','연동 설정']
  ];
  const subtitles={dashboard:'오늘 처리할 업무와 핵심 성과를 확인하세요.',clients:'고객의 운영 기준과 계약 정보를 관리합니다.',analysis:'최근 게시글에서 운영 방향을 찾아 확정합니다.',compose:'확정된 고객 기준으로 작성 프롬프트를 만듭니다.',board:'원고 상태와 수정 이력을 한눈에 관리합니다.',performance:'24시간과 7일 성과를 분리해 기록합니다.',reports:'저장된 성과로 고객용 보고서를 만듭니다.',requests:'사진·영상·승인 요청의 마감을 놓치지 않습니다.',backup:'모든 업무 데이터를 파일로 안전하게 옮깁니다.',integration:'Threads API 연결 상태와 동기화를 관리합니다.'};
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  function load(){try{return JSON.parse(localStorage.getItem(KEY))||structuredClone(defaultData)}catch{return structuredClone(defaultData)}}
  function save(){localStorage.setItem(KEY,JSON.stringify(data)); refreshClientSelect()}
  function client(){return data.clients.find(x=>x.id===selectedClient)||data.clients[0]}
  function fmt(n){return n===null||n===undefined||n===''?'집계 전':Number(n).toLocaleString('ko-KR')}
  function date(v){return v?new Date(v).toLocaleDateString('ko-KR'):'—'}
  function reaction(p){return ['likes','comments','reposts','shares'].reduce((s,k)=>s+(Number(p?.[k])||0),0)}
  function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}
  function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
  function refreshClientSelect(){const sel=$('#globalClient');if(!sel)return;sel.innerHTML=data.clients.map(c=>`<option value="${c.id}" ${c.id===selectedClient?'selected':''}>${esc(c.company)}</option>`).join('')}
  function renderNav(){ $('#mainNav').innerHTML=navItems.map(([id,ic,label])=>`<button class="nav-btn ${id===route?'active':''}" data-route="${id}"><span class="nav-icon">${ic}</span>${label}</button>`).join('') }
  function go(id){route=id; const item=navItems.find(x=>x[0]===id);$('#pageTitle').textContent=item?.[2]||'';$('#pageSubtitle').textContent=subtitles[id]||'';renderNav();render();$('#sidebar').classList.remove('open');scrollTo(0,0)}
  function render(){const views={dashboard,clients,analysis,compose,board,performance,reports,requests,backup,integration};$('#workspace').innerHTML=views[route]();bindRoute()}
  const stat=(label,value,meta='')=>`<article class="stat-card"><div class="stat-label">${label}</div><div class="stat-value">${value}</div>${meta?`<div class="stat-meta">${meta}</div>`:''}</article>`;
  function dashboard(){
    const cs=data.contents.filter(x=>x.clientId===selectedClient), ps=data.performance.filter(p=>cs.some(c=>c.id===p.contentId));
    const weekViews=ps.reduce((s,p)=>s+(+p.views||0),0), weekReact=ps.reduce((s,p)=>s+reaction(p),0), pending=data.requests.filter(x=>x.clientId===selectedClient&&x.status!=='사용 완료'&&x.status!=='자료 확보').length;
    return `<section class="section"><div class="stats-grid grid">${stat('오늘 작성할 글',cs.filter(x=>x.writeDate===today.toISOString().slice(0,10)).length,'작성 예정')}${stat('고객에게 전달할 글',cs.filter(x=>x.status==='고객 확인 중').length,'확인 대기')}${stat('오늘 발행할 글',cs.filter(x=>x.schedule?.slice(0,10)===today.toISOString().slice(0,10)).length,'예약 확인')}${stat('수정이 필요한 글',cs.filter(x=>x.status==='수정 필요').length,'피드백 반영')}${stat('이번 주 발행 수',cs.filter(x=>x.status==='발행 완료').length+'개','월간 목표 '+client().monthlyGoal+'개')}${stat('이번 주 평균 조회수',ps.length?fmt(Math.round(weekViews/ps.length)):'집계 전','동일 성과 기준')}${stat('이번 주 총 반응',fmt(weekReact),'좋아요·댓글·리포스트·공유')}${stat('자료 요청 미완료',pending+'건','마감 전 확인')}</div></section>
    <section class="grid two-col section"><article class="card"><div class="section-head"><div><h2>이번 주 운영 흐름</h2><p>${esc(client().company)} 진행 상황</p></div><button class="btn small outline" data-route="board">보드 보기</button></div><div class="list">${cs.map(c=>`<div class="list-item"><div class="row space"><strong>${esc(c.title)}</strong><span class="badge ${c.status==='발행 완료'?'':'navy'}">${c.status}</span></div><div class="row small-text muted" style="margin-top:8px"><span>${c.type}</span><span>·</span><span>${c.schedule?date(c.schedule):'일정 미정'}</span></div></div>`).join('')}</div></article>
    <article class="card"><div class="section-head"><div><h2>최근 Threads 동기화</h2><p>데모 모드 · API 연결 전</p></div><span class="badge">정상</span></div><div class="notice">마지막 동기화 ${new Date(client().lastSync).toLocaleString('ko-KR')} · 최근 30일 게시글 ${data.posts.filter(p=>p.clientId===selectedClient).length}개</div><div class="chart">${data.posts.filter(p=>p.clientId===selectedClient&&!p.excluded).slice(0,5).reverse().map(p=>`<div class="bar-wrap"><div class="bar" style="height:${Math.max(18,p.views/30)}px"></div><small>${new Date(p.date).getMonth()+1}/${new Date(p.date).getDate()}</small></div>`).join('')}</div></article></section>`;
  }
  function clients(){const c=client();return `<section class="grid two-col"><form class="card" id="clientForm"><div class="section-head"><div><h2>고객 운영 기준</h2><p>확정된 정보는 콘텐츠 작성에 자동 반영됩니다.</p></div><span class="badge">${c.confirmed?'확정됨':'확정 전'}</span></div><div class="form-grid">${field('company','업체명',c.company)}${field('industry','업종',c.industry)}${field('target','타깃 고객',c.target,'textarea')}${field('purpose','계정 운영 목적',c.purpose,'textarea')}${field('tone','브랜드 말투',c.tone,'textarea')}${field('banned','금지 표현',c.banned,'textarea')}${field('services','주요 상품과 서비스',c.services,'textarea')}${field('references','참고 게시글',c.references,'textarea')}${field('manager','담당자명',c.manager)}${field('contact','연락처',c.contact)}${field('contractStart','계약 시작일',c.contractStart,'date')}${field('contractEnd','계약 종료일',c.contractEnd,'date')}${field('monthlyGoal','월간 발행 목표',c.monthlyGoal,'number')}${field('threads','Threads 계정 URL',c.threads)}${field('requests','고객 요청사항',c.requests,'textarea','span-2')}</div><div class="actions"><button class="btn" type="submit">고객 정보 저장</button><button class="btn secondary" type="button" data-action="sync">Threads 계정 불러오기</button></div></form><aside class="card"><div class="section-head"><div><h2>계정 프로필</h2><p>최근 불러온 공개 정보</p></div><span class="badge navy">@${esc(c.username)}</span></div><div class="list"><div class="list-item"><strong>${esc(c.profileName)}</strong><p class="muted">${esc(c.bio)}</p><a href="${esc(c.threads)}" target="_blank">계정 열기 ↗</a></div><div class="notice">API가 없어도 데모·직접 입력·CSV/JSON 가져오기로 모든 기능을 테스트할 수 있습니다.</div></div><div class="actions"><button class="btn outline" data-action="new-client">+ 새 고객</button></div></aside></section>`}
  function field(name,label,value,type='text',cls=''){return `<div class="field ${cls}"><label for="${name}">${label}</label>${type==='textarea'?`<textarea id="${name}" name="${name}">${esc(value)}</textarea>`:`<input id="${name}" name="${name}" type="${type}" value="${esc(value)}" />`}</div>`}
  function analysis(){const c=client(),a=c.analysis, posts=data.posts.filter(p=>p.clientId===selectedClient);return `<section class="section"><div class="section-head"><div><h2>계정 분석</h2><p>최근 30일 게시글 ${posts.length}개 · 답글/리포스트 ${data.settings.includeReplies?'포함':'제외'}</p></div><div class="actions" style="margin:0"><button class="btn outline" data-action="add-post">게시글 직접 등록</button><button class="btn secondary" data-action="import-posts">CSV·JSON 가져오기</button></div></div><div class="grid two-col"><article class="card"><div class="row space"><h2 style="font-size:1rem">AI 추천값</h2><span class="badge warn">확정 전 검토</span></div><div class="form-grid" id="analysisForm">${Object.entries({industry:'추정 업종',target:'주요 타깃 고객',purpose:'현재 운영 목적',themes:'자주 다루는 주제',tone:'브랜드 말투와 문장 특징',hooks:'자주 사용하는 후킹',services:'주요 상품과 서비스',best:'반응이 좋았던 유형',missing:'부족한 콘텐츠',direction:'추천 콘텐츠 방향',caution:'확인 필요 표현'}).map(([k,l])=>field('an_'+k,l,a[k]||'','textarea')).join('')}</div><div class="notice warning" style="margin-top:14px">‘확인 필요 표현’은 금지 표현으로 자동 확정되지 않습니다. 검토 후 고객 관리에서 직접 입력하세요.</div><div class="actions"><button class="btn" data-action="confirm-analysis">고객 운영 기준으로 확정</button><button class="btn outline" data-action="reanalyze">추천값 다시 생성</button></div></article><article class="card"><div class="row space"><h2 style="font-size:1rem">최근 게시글</h2><div class="tabs"><button class="tab ${postView==='card'?'active':''}" data-view="card">카드</button><button class="tab ${postView==='list'?'active':''}" data-view="list">목록</button></div></div><div class="filterbar" style="margin:12px 0"><select id="postFilter"><option value="all">전체 유형</option><option>정보</option><option>공감</option><option>홍보</option><option>브랜드</option></select><select id="postSort"><option value="date">최신순</option><option value="high">반응 높은 순</option></select></div><div id="postContainer">${renderPosts(posts)}</div></article></div></section>`}
  function renderPosts(posts){let arr=[...posts];if(postView==='list')return `<div class="list">${arr.map(postItem).join('')}</div>`;return `<div class="post-grid" style="grid-template-columns:1fr">${arr.map(postCard).join('')}</div>`}
  function postCard(p){return `<article class="post-card"><div class="row space"><span class="badge ${p.kind==='일반'?'':'warn'}">${p.kind} · ${p.format}</span><small class="muted">${date(p.date)}</small></div><div class="post-text">${esc(p.text)}</div><div class="metrics"><span>조회 ${fmt(p.views)}</span><span>♥ ${fmt(p.likes)}</span><span>댓글 ${fmt(p.comments)}</span><span>↻ ${fmt(p.reposts)}</span></div><div class="post-actions"><button class="btn small outline" data-post-action="reference" data-id="${p.id}">참고자료</button><button class="btn small outline" data-post-action="performance" data-id="${p.id}">성과 분석</button><button class="btn small outline" data-post-action="featured" data-id="${p.id}">${p.featured?'대표 해제':'대표 지정'}</button><button class="btn small danger" data-post-action="exclude" data-id="${p.id}">${p.excluded?'분석 포함':'분석 제외'}</button></div></article>`}
  function postItem(p){return `<div class="list-item"><div class="row space"><strong>${esc(p.text.slice(0,42))}${p.text.length>42?'…':''}</strong><span class="badge">${p.category}</span></div><div class="metrics" style="margin-top:8px"><span>${date(p.date)}</span><span>${p.format}</span><span>반응 ${fmt((p.likes||0)+(p.comments||0)+(p.reposts||0))}</span></div></div>`}
  function compose(){const c=client();return `<section class="grid two-col"><article class="card"><div class="section-head"><div><h2>작성 조건</h2><p>${esc(c.company)} 확정 운영 기준을 자동 반영합니다.</p></div><span class="badge">운영 기준 ${c.confirmed?'확정':'미확정'}</span></div><form id="composeForm" class="form-grid">${field('topic','주제','가을 환절기 따뜻한 차 루틴')}${field('keywords','키워드','퇴근, 5분, 따뜻한 한 잔')}<div class="field"><label>글의 목적</label><select name="goal"><option>정보</option><option>공감</option><option>일상</option><option>질문</option><option>브랜드 이야기</option><option>상품 홍보</option><option>모집</option></select></div>${field('count','작성 개수',3,'number')}<div class="field span-2"><button class="btn" type="submit">프롬프트 만들기</button></div></form><div class="notice warning" id="duplicateNotice" style="margin-top:14px">최근 게시글의 ‘따뜻한 차 루틴’ 주제와 유사할 수 있습니다. 후킹 각도를 다르게 설정하세요.</div></article><aside class="card"><h2 style="font-size:1rem">자동 반영되는 고객 기준</h2><div class="list small-text"><div class="list-item"><strong>타깃</strong><p>${esc(c.target)}</p></div><div class="list-item"><strong>말투</strong><p>${esc(c.tone)}</p></div><div class="list-item"><strong>금지 표현</strong><p>${esc(c.banned)}</p></div><div class="list-item"><strong>최근 성과 우수 유형</strong><p>${esc(c.analysis.best)}</p></div><div class="list-item"><strong>최근 주제·후킹</strong><p>${esc(c.analysis.themes)} · ${esc(c.analysis.hooks)}</p></div></div></aside></section><section class="card section" id="promptResult" style="margin-top:16px"><div class="section-head"><div><h2>생성 프롬프트</h2><p>외부 AI에 붙여넣고 결과를 다시 저장하세요.</p></div><button class="btn secondary" data-action="copy-prompt">전체 복사</button></div><textarea id="promptText" style="width:100%;min-height:220px;border:1px solid var(--line);border-radius:10px;padding:14px">${esc(makePrompt('가을 환절기 따뜻한 차 루틴','퇴근, 5분, 따뜻한 한 잔','정보',3))}</textarea><div class="actions"><button class="btn outline" data-action="paste-result">AI 결과 붙여넣어 콘텐츠로 저장</button></div></section>`}
  function makePrompt(topic,keywords,goal,count){const c=client();return `[역할]\n당신은 ${c.company}의 Threads 콘텐츠 작가입니다.\n\n[운영 기준]\n- 업종: ${c.industry}\n- 타깃: ${c.target}\n- 계정 목적: ${c.purpose}\n- 브랜드 말투: ${c.tone}\n- 금지 표현: ${c.banned}\n- 주요 상품·서비스: ${c.services}\n- 최근 반응 우수 유형: ${c.analysis.best}\n- 최근 사용 주제·후킹: ${c.analysis.themes} / ${c.analysis.hooks}\n\n[작성 요청]\n- 주제: ${topic}\n- 키워드: ${keywords}\n- 목적: ${goal}\n- 개수: ${count}개\n- Threads에 바로 게시할 수 있게 각 원고를 번호로 구분하세요.\n- 첫 문장은 실제 후킹으로 강하게 시작하되 과장하지 마세요.\n- 최근 콘텐츠와 같은 문장·후킹을 반복하지 마세요.\n- 각 원고 아래에 콘텐츠 유형과 추천 이미지 한 줄을 덧붙이세요.`}
  const statuses=['아이디어','작성 중','고객 확인 중','수정 필요','승인','발행 완료'];
  function board(){const cs=data.contents.filter(c=>c.clientId===selectedClient);return `<section class="section"><div class="section-head"><div><h2>콘텐츠 칸반</h2><p>카드를 끌어 상태를 변경할 수 있습니다.</p></div><div class="actions" style="margin:0"><button class="btn secondary" data-action="copy-delivery">고객 전달용 전체 복사</button><button class="btn" data-action="new-content">+ 콘텐츠 등록</button></div></div><div class="kanban">${statuses.map(s=>`<div class="kanban-col" data-status="${s}"><div class="kanban-head"><span>${s}</span><span class="badge navy">${cs.filter(c=>c.status===s).length}</span></div>${cs.filter(c=>c.status===s).map(contentCard).join('')}</div>`).join('')}</div></section>`}
  function contentCard(c){const missing=data.requests.some(r=>r.contentId===c.id&&!['자료 확보','사용 완료'].includes(r.status));return `<article class="content-card" draggable="true" data-content="${c.id}"><div class="row space"><span class="badge">${c.type}</span>${missing?'<span class="badge red">자료 미확보</span>':''}</div><h3>${esc(c.title)}</h3><p>${esc(c.hook)}</p><div class="row space" style="margin-top:10px"><small class="muted">${c.schedule?date(c.schedule):'일정 미정'}</small><button class="btn small outline" data-edit-content="${c.id}">상세</button></div></article>`}
  function performance(){const cs=data.contents.filter(c=>c.clientId===selectedClient&&c.status==='발행 완료');return `<section class="section"><div class="section-head"><div><h2>게시글별 성과</h2><p>24시간과 7일 성과를 분리해 비교합니다.</p></div><button class="btn" data-action="add-performance">+ 성과 입력</button></div><div class="stats-grid grid">${stat('24시간 평균 조회수',avgFor('24h','views'))}${stat('7일 평균 조회수',avgFor('7d','views'))}${stat('24시간 평균 반응',avgReact('24h'))}${stat('7일 평균 반응',avgReact('7d'))}</div></section><section class="table-wrap"><table><thead><tr><th>콘텐츠</th><th>기준</th><th>조회수</th><th>좋아요</th><th>댓글</th><th>리포스트</th><th>총 반응</th><th></th></tr></thead><tbody>${cs.map(c=>{const ps=data.performance.filter(p=>p.contentId===c.id);return ps.length?ps.map(p=>`<tr><td><strong>${esc(c.title)}</strong></td><td><span class="badge">${p.window==='24h'?'24시간':'7일'}</span></td><td>${fmt(p.views)}</td><td>${fmt(p.likes)}</td><td>${fmt(p.comments)}</td><td>${fmt(p.reposts)}</td><td><strong>${fmt(reaction(p))}</strong></td><td><button class="btn small outline" data-edit-performance="${p.id}">수정</button></td></tr>`).join(''):`<tr><td><strong>${esc(c.title)}</strong></td><td colspan="6" class="muted">집계 전</td><td><button class="btn small outline" data-perf-content="${c.id}">입력</button></td></tr>`}).join('')}</tbody></table></section><div class="notice" style="margin-top:14px">입력되지 않은 값은 0이 아닌 ‘집계 전’로 표시합니다. 24시간·7일 데이터는 서로 섞어 평균내지 않습니다.</div>`}
  function avgFor(w,k){const ps=data.performance.filter(p=>p.window===w&&p[k]!==null&&p[k]!==undefined);return ps.length?fmt(Math.round(ps.reduce((s,p)=>s+(+p[k]||0),0)/ps.length)):'집계 전'}
  function avgReact(w){const ps=data.performance.filter(p=>p.window===w);return ps.length?fmt(Math.round(ps.reduce((s,p)=>s+reaction(p),0)/ps.length)):'집계 전'}
  function reports(){return `<section class="section no-print"><div class="section-head"><div><h2>클라이언트 보고서</h2><p>콘텐츠와 성과 기록에서 자동 집계합니다.</p></div><div class="actions" style="margin:0"><select id="reportType"><option value="weekly">주간 보고서</option><option value="monthly">월간 보고서</option></select><button class="btn" data-action="generate-report">보고서 새로 생성</button></div></div><div class="actions"><button class="btn secondary" data-action="save-report">현재 보고서 저장</button><button class="btn outline" data-action="copy-report">전체 내용 복사</button><button class="btn outline" data-action="print-report">인쇄 · PDF 저장</button><button class="btn outline" data-action="old-reports">이전 보고서 (${data.reports.filter(r=>r.clientId===selectedClient).length})</button></div></section><div id="reportArea">${weeklyReport()}</div>`}
  function reportData(){const cs=data.contents.filter(c=>c.clientId===selectedClient&&c.status==='발행 완료'), ps=data.performance.filter(p=>cs.some(c=>c.id===p.contentId)&&p.window==='24h');return {cs,ps,views:ps.reduce((s,p)=>s+(+p.views||0),0),likes:ps.reduce((s,p)=>s+(+p.likes||0),0),comments:ps.reduce((s,p)=>s+(+p.comments||0),0),reposts:ps.reduce((s,p)=>s+(+p.reposts||0),0),react:ps.reduce((s,p)=>s+reaction(p),0),follows:ps.reduce((s,p)=>s+(+p.follows||0),0),visits:ps.reduce((s,p)=>s+(+p.profileVisits||0),0),clicks:ps.reduce((s,p)=>s+(+p.clicks||0),0),inquiries:ps.reduce((s,p)=>s+(+p.inquiries||0),0),purchases:ps.reduce((s,p)=>s+(+p.purchases||0),0)}}
  function weeklyReport(){const r=reportData(), best=[...r.ps].sort((a,b)=>(b.views+reaction(b))-(a.views+reaction(a))).slice(0,3);return `<article class="report" id="printableReport"><div class="report-title"><span class="badge">주간 보고서</span><h1>${esc(client().company)}</h1><p class="muted">${new Date().toLocaleDateString('ko-KR')} 기준 · 자동 집계</p></div><h2>① 이번 주 핵심 성과</h2><div class="report-kpis"><div class="report-kpi"><span>발행</span><strong>${r.cs.length}개</strong></div><div class="report-kpi"><span>총 조회수</span><strong>${fmt(r.views)}</strong></div><div class="report-kpi"><span>평균 조회수</span><strong>${r.ps.length?fmt(Math.round(r.views/r.ps.length)):'집계 전'}</strong></div><div class="report-kpi"><span>총 반응</span><strong>${fmt(r.react)}</strong></div><div class="report-kpi"><span>좋아요</span><strong>${fmt(r.likes)}</strong></div><div class="report-kpi"><span>댓글</span><strong>${fmt(r.comments)}</strong></div><div class="report-kpi"><span>신규 팔로워</span><strong>${fmt(r.follows)}</strong></div><div class="report-kpi"><span>문의·구매</span><strong>${fmt(r.inquiries)} · ${fmt(r.purchases)}</strong></div></div><h2>② 성과가 좋았던 콘텐츠</h2>${best.length?best.map((p,i)=>{const c=data.contents.find(x=>x.id===p.contentId);return `<div class="list-item"><strong>${i+1}. ${esc(c.hook)}</strong><p>${c.purpose} · ${c.type} · 조회 ${fmt(p.views)} · 반응 ${fmt(reaction(p))}</p><p class="muted">${esc(p.reasonHigh||p.reaction||'성과 원인 기록 필요')} 다음 콘텐츠에는 ${esc(p.next||'효과적인 요소를 재활용합니다.')}</p></div>`}).join(''):'<div class="empty">집계된 콘텐츠가 없습니다.</div>'}<h2>③ 고객 반응</h2><p>${esc(best[0]?.commentsText||'반복 질문과 구매 의도 댓글을 기록하면 자동 반영됩니다.')}</p><p><strong>전환 가능 반응:</strong> ${esc(best[0]?.conversion||'확인 가능한 반응 없음')}</p><h2>④ 다음 주 운영 계획</h2><ul><li>체크리스트형 정보 콘텐츠와 생활 장면 공감 콘텐츠를 강화합니다.</li><li>다음 주 발행 예정 4개, 핵심 목표는 저장·공유 반응 확대입니다.</li><li>제품 설명만으로 시작하는 홍보형 콘텐츠는 줄이고 사용 상황을 먼저 제시합니다.</li></ul><h2>⑤ 자료와 확인 요청</h2>${pendingRequests()}</article>`}
  function monthlyReport(){const r=reportData();return `<article class="report" id="printableReport"><div class="report-title"><span class="badge navy">월간 보고서</span><h1>${esc(client().company)}</h1><p class="muted">${new Date().getFullYear()}년 ${new Date().getMonth()+1}월 · 자동 집계</p></div><h2>① 월간 성과 요약</h2><div class="report-kpis"><div class="report-kpi"><span>총 발행</span><strong>${r.cs.length}개</strong></div><div class="report-kpi"><span>총 조회수</span><strong>${fmt(r.views)}</strong></div><div class="report-kpi"><span>평균 조회수</span><strong>${r.ps.length?fmt(Math.round(r.views/r.ps.length)):'집계 전'}</strong></div><div class="report-kpi"><span>총 반응</span><strong>${fmt(r.react)}</strong></div></div><h2>② 지난달 대비 변화</h2><div class="notice">비교 데이터 없음 — 지난달 보고서가 저장되면 증감률을 계산합니다.</div><h2>③ 베스트 콘텐츠</h2>${weeklyReport().match(/<h2>②[\s\S]*?<h2>③/)?.[0].replace(/<h2>②[^<]*<\/h2>/,'').replace('<h2>③','')||''}<h2>④ 콘텐츠 유형별 분석</h2><div class="table-wrap"><table><thead><tr><th>유형</th><th>발행 수</th><th>평균 조회수</th><th>평균 반응</th></tr></thead><tbody>${['정보형','공감·질문형','브랜드 이야기','상품 홍보형','일상·현장형'].map(t=>{const cc=r.cs.filter(c=>c.type===t),pp=r.ps.filter(p=>cc.some(c=>c.id===p.contentId));return `<tr><td>${t}</td><td>${cc.length}</td><td>${pp.length?fmt(Math.round(pp.reduce((s,p)=>s+p.views,0)/pp.length)):'데이터 없음'}</td><td>${pp.length?fmt(Math.round(pp.reduce((s,p)=>s+reaction(p),0)/pp.length)):'데이터 없음'}</td></tr>`}).join('')}</tbody></table></div><h2>⑤ 이번 달 핵심 인사이트</h2><p>구체적인 선물 상황과 선택 기준을 제시한 정보형 콘텐츠에서 저장·공유와 상담 반응이 확인됐습니다. 제품을 바로 설명하기보다 고객의 선택 고민을 먼저 보여주는 구성이 효과적입니다.</p><h2>⑥ 다음 달 운영 방향</h2><ul><li>선물 선택 가이드와 원료 이야기 콘텐츠 확대</li><li>생활 장면이 약한 직접 홍보 콘텐츠 수정</li><li>고객 후기 기반 질문형 콘텐츠 테스트</li><li>발행 목표 ${client().monthlyGoal}개, 프로필 방문과 문의 증가 추적</li></ul><h3>필요 자료와 협조사항</h3>${pendingRequests()}</article>`}
  function pendingRequests(){const rs=data.requests.filter(x=>x.clientId===selectedClient&&!['자료 확보','사용 완료'].includes(x.status));return rs.length?rs.map(x=>`<div class="list-item"><strong>${esc(x.item)}</strong><p>${x.status} · ${date(x.due)}까지 · ${esc(x.reply||'답변 대기')}</p></div>`).join(''):'<p class="muted">미완료 요청이 없습니다.</p>'}
  function requests(){const rs=data.requests.filter(r=>r.clientId===selectedClient);return `<section class="section"><div class="section-head"><div><h2>이미지와 자료 요청</h2><p>연결 콘텐츠의 발행 전 확보 여부를 확인합니다.</p></div><button class="btn" data-action="new-request">+ 요청 등록</button></div><div class="stats-grid grid">${stat('미완료 요청',rs.filter(x=>!['자료 확보','사용 완료'].includes(x.status)).length+'건')}${stat('최우선',rs.filter(x=>x.priority==='최우선').length+'건')}${stat('이번 주 마감',rs.filter(x=>x.due).length+'건')}${stat('자료 확보',rs.filter(x=>x.status==='자료 확보').length+'건')}</div></section><section class="table-wrap"><table><thead><tr><th>요청 자료</th><th>사용 목적</th><th>마감일</th><th>우선순위</th><th>상태</th><th>고객 답변</th><th></th></tr></thead><tbody>${rs.map(r=>`<tr><td><strong>${esc(r.item)}</strong></td><td>${esc(r.purpose)}</td><td>${date(r.due)}</td><td><span class="badge ${r.priority==='최우선'?'red':'navy'}">${r.priority}</span></td><td>${r.status}</td><td>${esc(r.reply||'—')}</td><td><button class="btn small outline" data-edit-request="${r.id}">수정</button></td></tr>`).join('')}</tbody></table></section>`}
  function backup(){return `<section class="grid two-col"><article class="card"><h2>JSON 백업</h2><p class="muted">고객, 게시글, 콘텐츠, 성과, 보고서, 자료 요청을 한 파일로 내보냅니다.</p><div class="actions"><button class="btn" data-action="export-json">전체 데이터 내보내기</button><button class="btn outline" data-action="import-backup">백업 파일 가져오기</button></div><div class="notice" style="margin-top:16px">가져오기 전 현재 데이터는 자동으로 보존되지 않습니다. 먼저 내보내기를 권장합니다.</div></article><article class="card"><h2>저장 상태</h2><div class="list"><div class="list-item row space"><span>고객</span><strong>${data.clients.length}명</strong></div><div class="list-item row space"><span>최근 게시글</span><strong>${data.posts.length}개</strong></div><div class="list-item row space"><span>콘텐츠</span><strong>${data.contents.length}개</strong></div><div class="list-item row space"><span>성과 기록</span><strong>${data.performance.length}개</strong></div><div class="list-item row space"><span>저장 보고서</span><strong>${data.reports.length}개</strong></div></div><div class="actions"><button class="btn danger" data-action="reset-demo">데모 데이터로 초기화</button></div></article></section>`}
  function integration(){const c=client();return `<section class="grid two-col"><article class="card"><div class="section-head"><div><h2>Meta Threads API</h2><p>공식 OAuth 연동 준비</p></div><span class="badge ${data.settings.apiConnected?'':'warn'}">${data.settings.apiConnected?'연결됨':'연결 안 됨'}</span></div><div class="list"><div class="list-item row space"><span>연결 상태</span><strong>${data.settings.apiConnected?'정상':'데모 모드'}</strong></div><div class="list-item row space"><span>계정</span><strong>@${esc(c.username)}</strong></div><div class="list-item row space"><span>마지막 동기화</span><strong>${new Date(c.lastSync).toLocaleString('ko-KR')}</strong></div></div><div class="actions"><button class="btn" data-action="connect-api">계정 연결</button><button class="btn outline" data-action="sync">다시 동기화</button><button class="btn danger" data-action="disconnect-api">연결 해제</button></div></article><article class="card"><h2>안전한 연동 구조</h2><div class="notice">MVP에서는 토큰과 비밀키를 브라우저에 저장하지 않습니다. 실제 연결 시 서버 환경변수와 OAuth 콜백을 사용하는 별도 어댑터로 교체할 수 있도록 분리되어 있습니다.</div><div class="list" style="margin-top:14px"><div class="list-item"><strong>현재 사용 가능</strong><p>데모 데이터, 직접 입력, 본문 붙여넣기, CSV·JSON 가져오기</p></div><div class="list-item"><strong>공식 API 연결 후</strong><p>최근 30일 게시글 동기화, 게시물 ID·URL 중복 방지, 공개 성과 업데이트</p></div></div></article></section>`}

  function modal(title,html){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=html;$('#modalBackdrop').classList.remove('hidden')}
  function closeModal(){$('#modalBackdrop').classList.add('hidden')}
  function contentForm(c={}){return `<form id="contentForm" class="form-grid"><input type="hidden" name="id" value="${c.id||''}">${field('title','제목',c.title||'')}${field('hook','실제 후킹',c.hook||'')}${field('body','게시글 본문',c.body||'','textarea','span-2')}<div class="field"><label>콘텐츠 유형</label><select name="type">${['정보형','공감·질문형','브랜드 이야기','상품 홍보형','일상·현장형'].map(x=>`<option ${x===c.type?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>발행 목적</label><select name="purpose">${['정보','공감','일상','질문','브랜드 이야기','상품 홍보','모집'].map(x=>`<option ${x===c.purpose?'selected':''}>${x}</option>`).join('')}</select></div>${field('media','사용할 이미지와 영상',c.media||'')}${field('schedule','발행 예정일과 시간',c.schedule?.slice(0,16)||'','datetime-local')}<div class="field"><label>진행 상태</label><select name="status">${statuses.map(x=>`<option ${x===c.status?'selected':''}>${x}</option>`).join('')}</select></div>${field('feedback','고객 피드백',c.feedback||'','textarea')}${field('before','수정 전 내용',c.before||'','textarea')}${field('final','최종 승인 내용',c.final||'','textarea')}${field('link','게시물 링크',c.link||'','text','span-2')}<div class="field span-2"><button class="btn" type="submit">콘텐츠 저장</button></div></form>`}
  function perfForm(contentId,id=''){const p=data.performance.find(x=>x.id===id)||{contentId,window:'24h'};const num=k=>field(k,{views:'조회수',likes:'좋아요',comments:'댓글',follows:'신규 팔로우',reposts:'리포스트',shares:'공유',profileVisits:'프로필 방문',clicks:'링크 클릭',inquiries:'상담 문의',purchases:'구매'}[k],p[k]??'','number');return `<form id="perfForm" class="form-grid"><input type="hidden" name="id" value="${p.id||''}"><div class="field span-2"><label>콘텐츠</label><select name="contentId">${data.contents.filter(c=>c.clientId===selectedClient&&c.status==='발행 완료').map(c=>`<option value="${c.id}" ${c.id===p.contentId?'selected':''}>${esc(c.title)}</option>`).join('')}</select></div><div class="field span-2"><label>집계 기준</label><select name="window"><option value="24h" ${p.window==='24h'?'selected':''}>발행 후 24시간</option><option value="7d" ${p.window==='7d'?'selected':''}>발행 후 7일</option></select></div>${['views','likes','comments','follows','reposts','shares','profileVisits','clicks','inquiries','purchases'].map(num).join('')}${field('commentsText','실제로 달린 주요 댓글',p.commentsText||'','textarea')}${field('reaction','고객 반응',p.reaction||'','textarea')}${field('conversion','전환 가능성이 나타난 반응',p.conversion||'','textarea')}${field('reasonHigh','성과가 발생한 이유',p.reasonHigh||'','textarea')}${field('reasonLow','성과가 낮았던 이유',p.reasonLow||'','textarea')}${field('next','다음 콘텐츠에 적용할 요소',p.next||'','textarea','span-2')}<div class="field span-2"><button class="btn" type="submit">성과 저장</button></div></form>`}
  function requestForm(r={}){return `<form id="requestForm" class="form-grid"><input type="hidden" name="id" value="${r.id||''}">${field('item','요청 자료',r.item||'')}${field('purpose','사용 목적',r.purpose||'')}<div class="field"><label>연결 콘텐츠</label><select name="contentId"><option value="">선택 안 함</option>${data.contents.filter(c=>c.clientId===selectedClient).map(c=>`<option value="${c.id}" ${c.id===r.contentId?'selected':''}>${esc(c.title)}</option>`).join('')}</select></div>${field('requested','요청일',r.requested||today.toISOString().slice(0,10),'date')}${field('due','마감일',r.due||'','date')}<div class="field"><label>우선순위</label><select name="priority">${['최우선','우선','추가'].map(x=>`<option ${x===r.priority?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>상태</label><select name="status">${['요청 예정','요청 완료','자료 확보','확인 필요','사용 완료'].map(x=>`<option ${x===r.status?'selected':''}>${x}</option>`).join('')}</select></div>${field('reply','고객 답변',r.reply||'','textarea')}${field('asset','확보한 파일 또는 링크',r.asset||'')}${field('caution','사용 시 주의사항',r.caution||'','textarea','span-2')}<div class="field span-2"><button class="btn" type="submit">자료 요청 저장</button></div></form>`}
  function bindRoute(){
    $('#clientForm')?.addEventListener('submit',e=>{e.preventDefault();Object.assign(client(),Object.fromEntries(new FormData(e.target)));client().monthlyGoal=+client().monthlyGoal;save();toast('고객 정보를 저장했습니다.')});
    $('#composeForm')?.addEventListener('submit',e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));$('#promptText').value=makePrompt(f.topic,f.keywords,f.goal,f.count);toast('프롬프트를 만들었습니다.')});
    $$('[data-view]').forEach(b=>b.onclick=()=>{postView=b.dataset.view;render()});
    $('#postFilter')?.addEventListener('change',e=>{$('#postContainer').innerHTML=renderPosts(data.posts.filter(p=>p.clientId===selectedClient&&(e.target.value==='all'||p.category===e.target.value)))});
    $('#postSort')?.addEventListener('change',e=>{let ps=data.posts.filter(p=>p.clientId===selectedClient);if(e.target.value==='high')ps.sort((a,b)=>(b.likes+b.comments+b.reposts)-(a.likes+a.comments+a.reposts));$('#postContainer').innerHTML=renderPosts(ps)});
    $$('[data-post-action]').forEach(b=>b.onclick=()=>{const p=data.posts.find(x=>x.id===b.dataset.id),a=b.dataset.postAction;if(a==='featured')p.featured=!p.featured;if(a==='exclude')p.excluded=!p.excluded;if(a==='reference')p.reference=true;if(a==='performance')p.forPerformance=true;save();render();toast('게시글 설정을 반영했습니다.')});
    $$('.content-card').forEach(c=>c.addEventListener('dragstart',e=>e.dataTransfer.setData('text/plain',c.dataset.content)));
    $$('.kanban-col').forEach(col=>{col.addEventListener('dragover',e=>e.preventDefault());col.addEventListener('drop',e=>{e.preventDefault();const c=data.contents.find(x=>x.id===e.dataTransfer.getData('text/plain'));if(c){c.status=col.dataset.status;c.history=(c.history||[]).concat({date:today.toISOString().slice(0,10),note:'상태 변경: '+c.status});save();render();toast('상태를 변경했습니다.')}})});
    $$('[data-edit-content]').forEach(b=>b.onclick=()=>modal('콘텐츠 상세 및 수정',contentForm(data.contents.find(x=>x.id===b.dataset.editContent))));
    $$('[data-edit-performance]').forEach(b=>b.onclick=()=>modal('성과 수정',perfForm('',b.dataset.editPerformance)));
    $$('[data-perf-content]').forEach(b=>b.onclick=()=>modal('성과 입력',perfForm(b.dataset.perfContent)));
    $$('[data-edit-request]').forEach(b=>b.onclick=()=>modal('자료 요청 수정',requestForm(data.requests.find(x=>x.id===b.dataset.editRequest))));
    $('#reportType')?.addEventListener('change',e=>$('#reportArea').innerHTML=e.target.value==='monthly'?monthlyReport():weeklyReport());
  }
  document.addEventListener('submit',e=>{
    if(e.target.id==='contentForm'){e.preventDefault();const f=Object.fromEntries(new FormData(e.target)),old=data.contents.find(x=>x.id===f.id);if(old)Object.assign(old,f);else data.contents.push({...f,id:'ct-'+Date.now(),clientId:selectedClient,writeDate:today.toISOString().slice(0,10),deliveryDate:'',published:'',history:[]});save();closeModal();go('board');toast('콘텐츠를 저장했습니다.')}
    if(e.target.id==='perfForm'){e.preventDefault();const f=Object.fromEntries(new FormData(e.target));['views','likes','comments','follows','reposts','shares','profileVisits','clicks','inquiries','purchases'].forEach(k=>f[k]=f[k]===''?null:+f[k]);const old=data.performance.find(x=>x.id===f.id);if(old)Object.assign(old,f);else data.performance.push({...f,id:'pf-'+Date.now()});save();closeModal();go('performance');toast('성과를 저장했습니다.')}
    if(e.target.id==='requestForm'){e.preventDefault();const f=Object.fromEntries(new FormData(e.target)),old=data.requests.find(x=>x.id===f.id);if(old)Object.assign(old,f);else data.requests.push({...f,id:'rq-'+Date.now(),clientId:selectedClient});save();closeModal();go('requests');toast('자료 요청을 저장했습니다.')}
    if(e.target.id==='postForm'){e.preventDefault();const f=Object.fromEntries(new FormData(e.target)),dup=data.posts.some(p=>p.id===f.postId||p.url===f.url);if(dup)return toast('같은 게시물 ID 또는 URL이 이미 있습니다.');data.posts.push({id:f.postId||'manual-'+Date.now(),clientId:selectedClient,date:f.date||iso(Date.now()),kind:f.kind||'일반',format:f.format||'텍스트',category:f.category||'정보',text:f.text,url:f.url,likes:null,comments:null,reposts:null,views:null,analyzed:false});client().lastSync=iso(Date.now());save();closeModal();go('analysis');toast('게시글을 등록했습니다.')}
  });
  document.addEventListener('click',async e=>{
    const b=e.target.closest('button');if(!b)return;if(b.dataset.route)return go(b.dataset.route);if(b.hasAttribute('data-close-modal'))return closeModal();const a=b.dataset.action;if(!a)return;
    if(a==='quick-content'||a==='new-content')modal('새 콘텐츠 등록',contentForm());
    if(a==='add-performance')modal('성과 입력',perfForm(data.contents.find(c=>c.clientId===selectedClient&&c.status==='발행 완료')?.id||''));
    if(a==='new-request')modal('새 자료 요청',requestForm());
    if(a==='add-post')modal('게시글 직접 등록',`<form id="postForm" class="form-grid">${field('postId','게시물 ID','')}${field('url','게시물 URL','')}${field('date','작성일과 시간',today.toISOString().slice(0,16),'datetime-local')}<div class="field"><label>게시물 구분</label><select name="kind"><option>일반</option><option>답글</option><option>리포스트</option></select></div><div class="field"><label>형식</label><select name="format"><option>텍스트</option><option>이미지</option><option>영상</option></select></div><div class="field"><label>콘텐츠 유형</label><select name="category"><option>정보</option><option>공감</option><option>일상</option><option>홍보</option><option>모집</option></select></div>${field('text','게시글 본문','','textarea','span-2')}<div class="field span-2"><button class="btn" type="submit">게시글 저장</button></div></form>`);
    if(a==='new-client')toast('MVP에서는 자연애한차 데이터로 전체 흐름을 체험할 수 있습니다.');
    if(a==='sync'){const existing=data.posts.filter(p=>p.clientId===selectedClient).length;client().lastSync=iso(Date.now());save();modal('동기화 완료',`<div class="stats-grid grid">${stat('새로 추가',0+'개')}${stat('중복 제외',existing+'개')}${stat('분석 완료',data.posts.filter(p=>p.analyzed&&!p.excluded).length+'개')}${stat('불러오기 실패',0+'개')}</div><p class="notice" style="margin-top:15px">게시물 ID와 URL 기준으로 중복을 제외했습니다. ${new Date().toLocaleString('ko-KR')}</p>`)}
    if(a==='confirm-analysis'){const c=client();Object.keys(c.analysis).forEach(k=>{const el=$('#an_'+k);if(el)c.analysis[k]=el.value});c.industry=c.analysis.industry;c.target=c.analysis.target;c.purpose=c.analysis.purpose;c.tone=c.analysis.tone;c.services=c.analysis.services;c.confirmed=true;save();render();toast('분석을 고객 운영 기준으로 확정했습니다.')}
    if(a==='reanalyze')toast('최근 게시글을 바탕으로 추천값을 새로 정리했습니다.');
    if(a==='copy-prompt'){await navigator.clipboard.writeText($('#promptText').value);toast('프롬프트를 복사했습니다.')}
    if(a==='paste-result')modal('AI 작성 결과 붙여넣기',`<div class="field"><label>번호로 구분된 원고</label><textarea id="aiPaste" style="min-height:240px" placeholder="1. 첫 번째 원고&#10;&#10;2. 두 번째 원고"></textarea></div><div class="actions"><button class="btn" data-action="save-ai-results">개별 콘텐츠로 저장</button></div>`);
    if(a==='save-ai-results'){const parts=$('#aiPaste').value.split(/\n\s*\d+[.)]\s*/).map(x=>x.trim()).filter(Boolean);parts.forEach((body,i)=>data.contents.push({id:'ct-'+Date.now()+'-'+i,clientId:selectedClient,title:body.split('\n')[0].slice(0,38),hook:body.split('\n')[0],body,type:'정보형',purpose:'정보',media:'',writeDate:today.toISOString().slice(0,10),deliveryDate:'',schedule:'',published:'',status:'아이디어',feedback:'',before:'',final:'',link:'',history:[]}));save();closeModal();go('board');toast(parts.length+'개 콘텐츠로 저장했습니다.')}
    if(a==='copy-delivery'){const t=data.contents.filter(c=>c.clientId===selectedClient&&['고객 확인 중','승인'].includes(c.status)).map((c,i)=>`${i+1}. ${c.title}\n\n${c.body}`).join('\n\n──────────\n\n');await navigator.clipboard.writeText(t);toast('고객 전달용 원고를 복사했습니다.')}
    if(a==='generate-report'){$('#reportArea').innerHTML=$('#reportType').value==='monthly'?monthlyReport():weeklyReport();toast('최신 데이터로 보고서를 만들었습니다.')}
    if(a==='save-report'){const type=$('#reportType')?.value||'weekly';data.reports.push({id:'rp-'+Date.now(),clientId:selectedClient,type,createdAt:iso(Date.now()),html:$('#reportArea').innerHTML});save();toast('현재 시점의 보고서를 저장했습니다.')}
    if(a==='copy-report'){await navigator.clipboard.writeText($('#printableReport').innerText);toast('보고서 전체 내용을 복사했습니다.')}
    if(a==='print-report')window.print();
    if(a==='old-reports'){const rs=data.reports.filter(r=>r.clientId===selectedClient);modal('이전 보고서',rs.length?`<div class="list">${rs.map(r=>`<button class="list-item" style="text-align:left" data-load-report="${r.id}"><strong>${r.type==='weekly'?'주간':'월간'} 보고서</strong><p>${new Date(r.createdAt).toLocaleString('ko-KR')}</p></button>`).join('')}</div>`:'<div class="empty">저장된 보고서가 없습니다.</div>')}
    if(a==='export-json'){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='threads-ops-backup-'+today.toISOString().slice(0,10)+'.json';link.click();URL.revokeObjectURL(url);toast('백업 파일을 만들었습니다.')}
    if(a==='import-backup'||a==='import-posts'){$('#fileInput').dataset.mode=a;$('#fileInput').click()}
    if(a==='reset-demo'){if(confirm('현재 데이터를 데모 상태로 초기화할까요?')){data=structuredClone(defaultData);save();selectedClient=data.clients[0].id;render();toast('데모 데이터로 초기화했습니다.')}}
    if(a==='connect-api')modal('Meta OAuth 연결 준비됨',`<div class="notice warning">실제 연결에는 Meta 앱 ID, 서버 OAuth 콜백, 서버 환경변수가 필요합니다. 토큰을 브라우저에 직접 입력하거나 저장하지 않도록 설계했습니다.</div><p>현재는 데모·수동 가져오기 모드로 모든 핵심 업무를 사용할 수 있습니다.</p>`);
    if(a==='disconnect-api'){data.settings.apiConnected=false;save();render();toast('연결 정보를 해제했습니다.')}
  });
  document.addEventListener('click',e=>{const b=e.target.closest('[data-load-report]');if(!b)return;const r=data.reports.find(x=>x.id===b.dataset.loadReport);closeModal();go('reports');setTimeout(()=>{$('#reportArea').innerHTML=r.html},0)});
  $('#fileInput').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{const text=await file.text(),mode=e.target.dataset.mode;if(mode==='import-backup'){const parsed=JSON.parse(text);if(!parsed.clients||!parsed.contents)throw Error();data=parsed;selectedClient=data.clients[0]?.id;save();go('dashboard');toast('백업 데이터를 가져왔습니다.')}else{let rows;if(file.name.endsWith('.json'))rows=JSON.parse(text);else{const [head,...lines]=text.split(/\r?\n/).filter(Boolean);const hs=head.split(',').map(x=>x.trim());rows=lines.map(l=>Object.fromEntries(l.split(',').map((v,i)=>[hs[i],v.trim()])))}let added=0,dup=0;(Array.isArray(rows)?rows:[rows]).forEach((r,i)=>{const id=r.id||r.postId||'import-'+Date.now()+'-'+i,url=r.url||'';if(data.posts.some(p=>p.id===id||(url&&p.url===url)))dup++;else{data.posts.push({id,clientId:selectedClient,date:r.date||iso(Date.now()),kind:r.kind||'일반',format:r.format||'텍스트',category:r.category||'정보',text:r.text||r.body||'',url,likes:r.likes?+r.likes:null,comments:r.comments?+r.comments:null,reposts:r.reposts?+r.reposts:null,views:r.views?+r.views:null,analyzed:false});added++}});save();go('analysis');modal('가져오기 완료',`<p>새로 추가 ${added}개 · 중복 제외 ${dup}개</p>`)} }catch{toast('파일 형식을 확인해 주세요.')}e.target.value=''});
  $('#mainNav').addEventListener('click',e=>{const b=e.target.closest('[data-route]');if(b)go(b.dataset.route)});
  $('#globalClient').addEventListener('change',e=>{selectedClient=e.target.value;render()});
  $('#openNav').onclick=()=>$('#sidebar').classList.add('open');$('#closeNav').onclick=()=>$('#sidebar').classList.remove('open');
  $('#modalBackdrop').addEventListener('click',e=>{if(e.target===$('#modalBackdrop'))closeModal()});
  // WebMCP: visible actions and agent actions share the same data store.
  if(document.modelContext?.registerTool){const register=(tool)=>document.modelContext.registerTool(tool);register({name:'read_workspace_summary',title:'운영 현황 읽기',description:'선택 고객의 콘텐츠, 성과, 미완료 자료 요청 수를 읽습니다.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:()=>({client:client().company,contents:data.contents.filter(c=>c.clientId===selectedClient).length,performance:data.performance.length,pendingRequests:data.requests.filter(r=>r.clientId===selectedClient&&!['자료 확보','사용 완료'].includes(r.status)).length})});register({name:'create_content_idea',title:'콘텐츠 아이디어 만들기',description:'현재 고객에게 새 콘텐츠 아이디어를 추가합니다.',inputSchema:{type:'object',properties:{title:{type:'string'},hook:{type:'string'},body:{type:'string'}},required:['title','hook','body'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:i=>{if(!i?.title||!i?.hook||!i?.body)throw Error('title, hook, body required');const id='ct-'+Date.now();data.contents.push({id,clientId:selectedClient,title:i.title,hook:i.hook,body:i.body,type:'정보형',purpose:'정보',status:'아이디어',history:[]});save();render();return{id,status:'아이디어'}}})}
  renderNav();refreshClientSelect();render();
})();
